# Generated by Django 5.1.7 on 2026-10-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('zarinpal', 'زرین\u200cپال (پرداخت مستقیم)'), ('snappay', 'اسنپ\u200cپی'), ('torobpay', 'ترب\u200cپی')], max_length=20, unique=True, verbose_name='درگاه')),
                ('title', models.CharField(help_text='مثلاً: پرداخت امن زرین\u200cپال', max_length=100, verbose_name='نام نمایشی در سایت')),
                ('is_enabled', models.BooleanField(default=False, help_text='فقط درگاه\u200cهای فعال در صفحه پرداخت نمایش داده می\u200cشوند', verbose_name='فعال')),
                ('is_sandbox', models.BooleanField(default=False, help_text='برای آزمایش فرآیند پرداخت بدون حساب واقعی (فقط زرین\u200cپال)', verbose_name='حالت تست (سندباکس)')),
                ('merchant_id', models.CharField(blank=True, help_text='زرین\u200cپال و ترب\u200cپی', max_length=120, verbose_name='مرچنت کد / شناسه درگاه')),
                ('client_id', models.CharField(blank=True, help_text='اسنپ\u200cپی', max_length=120, verbose_name='Client ID')),
                ('client_secret', models.CharField(blank=True, help_text='اسنپ\u200cپی', max_length=250, verbose_name='Client Secret')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیح کوتاه برای سایت')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
            ],
            options={
                'verbose_name': 'تنظیمات درگاه پرداخت',
                'verbose_name_plural': 'تنظیمات درگاه\u200cهای پرداخت',
                'ordering': ['order', 'key'],
            },
        ),
    ]
