# Generated by Django 5.1.7 on 2026-10-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_order_item_integrity'),
        ('payments', '0002_gatewaysettings'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('authority__gt', '')), fields=('authority',), name='payment_transaction_unique_authority'),
        ),
    ]
