# Generated by Django 5.1.7 on 2025-03-28 02:33

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('phone', models.EmailField(max_length=14, verbose_name='شماره تماس')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('date_send', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'تماس با ما',
                'ordering': ['-date_send'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_about_us', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='متن درباره ما')),
                ('text_contact_us', models.TextField(blank=True, null=True, verbose_name='متن تماس با ما')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='آدرس')),
                ('phone1', models.CharField(blank=True, max_length=14, null=True, verbose_name='شماره تلفن اول')),
                ('phone2', models.CharField(blank=True, max_length=14, null=True, verbose_name='شماره تلفن دوم')),
                ('email1', models.CharField(blank=True, max_length=250, null=True, verbose_name='ایمیل اول')),
                ('email2', models.CharField(blank=True, max_length=250, null=True, verbose_name='ایمیل دوم')),
                ('copy_right', models.CharField(max_length=255, verbose_name='متن کپی رایت')),
                ('instagram_link', models.CharField(blank=True, default='https://instagram.com/username', max_length=250, null=True, verbose_name='لینک اینستاگرام')),
                ('telegram_link', models.CharField(blank=True, default='https://t.me/username', max_length=250, null=True, verbose_name='لینک تلگرام')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
