# Generated by Django 5.1.7 on 2025-05-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contactus_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان بنر')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='تصویر بنر')),
                ('url', models.URLField(verbose_name='لینک مقصد')),
                ('banner_type', models.CharField(choices=[('main_slider', 'اسلایدر اصلی'), ('small_banner', 'بنر های کوچک (4 تایی)'), ('large_banner', 'بنر های بزرگ (2 تایی)'), ('single_banner', 'بنر تک')], max_length=20, verbose_name='نوع بنر')),
                ('status', models.CharField(choices=[('draft', 'پیش نویس شود'), ('published', 'منتشر شود')], default='published', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنر ها',
            },
        ),
    ]
