# Generated by Django 5.1.7 on 2026-10-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='فایل\u200cمارکت', max_length=100, verbose_name='نام سایت'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_slogan',
            field=models.CharField(blank=True, default='مارکت فایل، نرم\u200cافزار و محصولات مجازی', max_length=200, verbose_name='شعار سایت'),
        ),
    ]
