# Generated by Django 5.1.7 on 2026-10-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_site_name_sitesettings_site_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='توضیحات سئوی پیش\u200cفرض'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_meta_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='عنوان سئوی پیش\u200cفرض'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enamad_link',
            field=models.URLField(blank=True, help_text='اگر خالی باشد نشان در فوتر نمایش داده نمی\u200cشود', null=True, verbose_name='لینک نشان اینماد'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_description',
            field=models.TextField(blank=True, help_text='اگر خالی باشد متن پیش\u200cفرض نمایش داده می\u200cشود', verbose_name='متن معرفی فوتر'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='لینک لینکدین'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='اگر خالی باشد لوگوی متنی نمایش داده می\u200cشود', null=True, upload_to='settings/', verbose_name='لوگو (اختیاری)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='products_per_page',
            field=models.PositiveIntegerField(default=9, verbose_name='تعداد محصول در هر صفحه'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='samandehi_link',
            field=models.URLField(blank=True, help_text='اگر خالی باشد نشان در فوتر نمایش داده نمی\u200cشود', null=True, verbose_name='لینک نشان ساماندهی'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='لینک توییتر (X)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='لینک واتساپ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='لینک یوتیوب'),
        ),
    ]
