# Generated by Django 5.1.7 on 2026-10-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_default_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='bing_site_verification',
            field=models.CharField(blank=True, max_length=120, verbose_name='کد تأیید Bing Webmaster'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_site_verification',
            field=models.CharField(blank=True, max_length=120, verbose_name='کد تأیید Google Search Console'),
        ),
    ]
