# Generated by Django 5.1.7 on 2026-10-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_bing_site_verification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(max_length=500, unique=True, verbose_name='آدرس قدیمی')),
                ('new_path', models.CharField(max_length=500, verbose_name='آدرس جدید')),
                ('status_code', models.CharField(choices=[('301', 'دائمی (301)'), ('302', 'موقت (302)')], default='301', max_length=3, verbose_name='نوع ریدایرکت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('hits', models.PositiveIntegerField(default=0, editable=False, verbose_name='دفعات استفاده')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'ریدایرکت',
                'verbose_name_plural': 'ریدایرکت\u200cها',
                'ordering': ['old_path'],
            },
        ),
    ]
