# Generated by Django 5.2.17 on 2026-10-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ckeditor5_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], default='published', max_length=10, verbose_name='وضعیت'),
        ),
    ]
