# Generated by Django 5.1.7 on 2025-04-16 19:24

import ckeditor_uploader.fields
import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان برند')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='نامک')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/brands', verbose_name='تصویر برند')),
                ('views', models.IntegerField(default=0, verbose_name='بازدید ها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برند ها',
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='عنوان رنگ')),
                ('color_code', models.CharField(default='#000000', help_text='این یک کد رنگی پیش فرض است', max_length=20, unique=True, verbose_name='کد رنگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ ها',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='نامک')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products/categories', verbose_name='تصویر دسته بندی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='product.productcategory', verbose_name='دسته بندی والد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='', unique=True, verbose_name='شناسه محصول')),
                ('title', models.CharField(max_length=300, unique=True, verbose_name='عنوان محصول')),
                ('slug', models.SlugField(allow_unicode=True, max_length=300, unique=True, verbose_name='نامک')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات تکمیلی')),
                ('old_price', models.IntegerField(blank=True, null=True, verbose_name='قیمت قدیمی محصول')),
                ('price', models.IntegerField(verbose_name='قیمت محصول')),
                ('stock_count', models.IntegerField(verbose_name='تعداد موجود')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products', verbose_name='تصویر محصول')),
                ('status', models.CharField(choices=[('draft', 'پیش نویس شود'), ('published', 'منتشر شود')], default='published', max_length=10, verbose_name='وضعیت')),
                ('views', models.IntegerField(default=0, verbose_name='بازدید ها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='مدل')),
                ('weight', models.CharField(blank=True, max_length=5, null=True, verbose_name='وزن (کیلوگرم)')),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True, verbose_name='ابعاد (سانتی\u200c متر)')),
                ('operating_system', models.CharField(blank=True, max_length=50, null=True, verbose_name='سیستم عامل')),
                ('battery_capacity', models.CharField(blank=True, max_length=50, null=True, verbose_name='ظرفیت باتری')),
                ('ram', models.CharField(blank=True, max_length=50, null=True, verbose_name='حافظه موقت')),
                ('internal_memory', models.CharField(blank=True, max_length=50, null=True, verbose_name='حافظه داخلی')),
                ('camera_resolution', models.CharField(blank=True, max_length=50, null=True, verbose_name='رزولوشن دوربین')),
                ('connectivity', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع اتصال')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='فروشنده')),
                ('brand', models.ManyToManyField(blank=True, null=True, related_name='product_brands', to='product.productbrand', verbose_name='برند مربوطه')),
                ('category', models.ManyToManyField(related_name='categories', to='product.productcategory', verbose_name='دسته بندی مربوطه')),
                ('color', models.ManyToManyField(blank=True, null=True, related_name='colors', to='product.productcolor', verbose_name='رنگ')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='متن دیدگاه')),
                ('status', models.CharField(choices=[('draft', 'پیش نویس شود'), ('published', 'منتشر شود')], default='published', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده دیدگاه')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to='product.product', verbose_name='محصول مربوطه')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/products/product_images', verbose_name='تصاویر محصولات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصولات',
            },
        ),
    ]
