# Generated by Django 5.1.7 on 2025-04-25 00:51

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=7, max_length=20, prefix='mip-', unique=True, verbose_name='شناسه محصول'),
        ),
    ]
