# Generated by Django 5.1.7 on 2025-04-25 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productcategory_is_active_productcategory_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='updated_at',
        ),
    ]
