# Generated by Django 5.1.7 on 2025-05-15 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_productcategory_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='parent',
        ),
    ]
