# Generated by Django 5.1.7 on 2025-05-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_productcategory_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='antenna_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد آنتن'),
        ),
        migrations.AddField(
            model_name='product',
            name='antenna_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع آنتن'),
        ),
        migrations.AddField(
            model_name='product',
            name='bluetooth_version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نسخه بلوتوث'),
        ),
        migrations.AddField(
            model_name='product',
            name='body_material',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='جنس بدنه'),
        ),
        migrations.AddField(
            model_name='product',
            name='display_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='اندازه صفحه نمایش'),
        ),
        migrations.AddField(
            model_name='product',
            name='os_support',
            field=models.TextField(blank=True, null=True, verbose_name='قابلیت پشتیبانی از سیستم عامل\u200cهای'),
        ),
        migrations.AddField(
            model_name='product',
            name='power_source',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='منبع تغذیه'),
        ),
        migrations.AddField(
            model_name='product',
            name='processor_generation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نسل پردازنده'),
        ),
        migrations.AddField(
            model_name='product',
            name='processor_manufacturer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='سازنده پردازنده'),
        ),
        migrations.AddField(
            model_name='product',
            name='processor_series',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='سری پردازنده'),
        ),
        migrations.AddField(
            model_name='product',
            name='strap_material',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='جنس بند'),
        ),
    ]
