# Generated by Django 5.1.7 on 2025-05-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_antenna_count_product_antenna_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='antenna_count',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تعداد آنتن'),
        ),
    ]
