# Generated by Django 5.1.7 on 2025-06-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_antenna_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales_count',
            field=models.IntegerField(default=0, verbose_name='تعداد فروش'),
        ),
    ]
