# Generated by Django 5.1.7 on 2026-10-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_seo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ManyToManyField(blank=True, related_name='product_brands', to='product.productbrand', verbose_name='برند مربوطه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, related_name='colors', to='product.productcolor', verbose_name='رنگ'),
        ),
    ]
