# Generated by Django 5.1.7 on 2026-10-05 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_product_brand_alter_product_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='digital-products/', verbose_name='فایل محصول')),
                ('version', models.CharField(blank=True, max_length=30, verbose_name='نسخه')),
                ('download_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='تعداد دانلود')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_asset', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'فایل دیجیتال',
                'verbose_name_plural': 'فایل\u200cهای دیجیتال',
            },
        ),
    ]
