# Generated by Django 5.1.7 on 2026-10-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_digitalasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalasset',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, editable=False, verbose_name='حجم فایل'),
        ),
        migrations.AddField(
            model_name='digitalasset',
            name='file_type',
            field=models.CharField(blank=True, max_length=80, verbose_name='فرمت فایل'),
        ),
        migrations.AddField(
            model_name='digitalasset',
            name='preview_file',
            field=models.FileField(blank=True, null=True, upload_to='digital-previews/', verbose_name='فایل پیش\u200cنمایش'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='ویژه'),
        ),
        migrations.AddField(
            model_name='product',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='توضیح کوتاه'),
        ),
    ]
