# Generated by Django 5.1.7 on 2026-10-05 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_digitalasset_file_size_digitalasset_file_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['title'], 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
    ]
