# Generated by Django 5.1.7 on 2026-10-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_cartitem_unique_together_remove_order_address_and_more'),
        ('product', '0016_alter_product_options_alter_productcategory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AlterModelOptions(
            name='productbrand',
            options={'verbose_name': 'برند / سازنده', 'verbose_name_plural': 'برندها / سازنده\u200cها'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='antenna_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='antenna_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='battery_capacity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bluetooth_version',
        ),
        migrations.RemoveField(
            model_name='product',
            name='body_material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='camera_resolution',
        ),
        migrations.RemoveField(
            model_name='product',
            name='connectivity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='display_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='internal_memory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
        migrations.RemoveField(
            model_name='product',
            name='os_support',
        ),
        migrations.RemoveField(
            model_name='product',
            name='power_source',
        ),
        migrations.RemoveField(
            model_name='product',
            name='processor_generation',
        ),
        migrations.RemoveField(
            model_name='product',
            name='processor_manufacturer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='processor_series',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='product',
            name='strap_material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AddField(
            model_name='digitalasset',
            name='changelog',
            field=models.TextField(blank=True, help_text='هر خط یک مورد از تغییرات نسخه', verbose_name='تغییرات نسخه'),
        ),
        migrations.AddField(
            model_name='product',
            name='demo_url',
            field=models.URLField(blank=True, verbose_name='لینک پیش\u200cنمایش (دمو)'),
        ),
        migrations.AddField(
            model_name='product',
            name='documentation_url',
            field=models.URLField(blank=True, verbose_name='لینک مستندات'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_unlimited',
            field=models.BooleanField(default=True, help_text='اگر فعال باشد محدودیتی برای تعداد فروش و دانلود وجود ندارد', verbose_name='دانلود نامحدود'),
        ),
        migrations.AddField(
            model_name='product',
            name='license_type',
            field=models.CharField(choices=[('single', 'لایسنس تک\u200cکاربره'), ('multi', 'لایسنس چندکاربردی'), ('lifetime', 'لایسنس دائمی'), ('subscription', 'اشتراک دوره\u200cای'), ('gpl', 'متن\u200cباز (GPL)')], default='single', max_length=20, verbose_name='نوع لایسنس'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('template', 'قالب سایت'), ('plugin', 'افزونه'), ('script', 'اسکریپت و کد آماده'), ('software', 'نرم\u200cافزار'), ('design_file', 'فایل طراحی'), ('virtual', 'محصول مجازی')], default='template', help_text='قالب، افزونه، اسکریپت، نرم\u200cافزار، فایل طراحی یا محصول مجازی', max_length=20, verbose_name='نوع محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='requirements',
            field=models.TextField(blank=True, help_text='هر خط یک پیش\u200cنیاز است، مثلاً: PHP 8.1+', verbose_name='پیش\u200cنیازها'),
        ),
        migrations.AddField(
            model_name='product',
            name='support_duration',
            field=models.CharField(blank=True, max_length=60, verbose_name='مدت پشتیبانی'),
        ),
        migrations.AddField(
            model_name='product',
            name='update_duration',
            field=models.CharField(blank=True, max_length=60, verbose_name='مدت دریافت به\u200cروزرسانی'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='نام آیکون Font Awesome مثلاً fa-wordpress', max_length=100, verbose_name='آیکون'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ManyToManyField(blank=True, related_name='product_brands', to='product.productbrand', verbose_name='برند / سازنده'),
        ),
        migrations.AlterField(
            model_name='product',
            name='operating_system',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سیستم عامل سازگار'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_count',
            field=models.IntegerField(default=0, help_text='برای محصولات با دانلود نامحدود نیازی به این عدد نیست', verbose_name='تعداد موجود (برای لایسنس محدود)'),
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
    ]
