# Generated by Django 5.2.17 on 2026-10-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_ckeditor5_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], default='published', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], default='published', max_length=10, verbose_name='وضعیت'),
        ),
    ]
