# Generated by Django 5.1.7 on 2026-10-05 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticpage',
            options={'ordering': ['title'], 'verbose_name': 'صفحه', 'verbose_name_plural': 'صفحات'},
        ),
    ]
