# Generated by Django 5.1.7 on 2026-10-05 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان پروژه')),
                ('image', models.ImageField(upload_to='images/portfolio/', verbose_name='تصویر نمونه کار')),
                ('url', models.URLField(blank=True, verbose_name='آدرس سایت')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='دسته (شرکتی، فروشگاهی، ...)')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'نمونه کار',
                'verbose_name_plural': 'نمونه کارها',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان پکیج')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='توضیح کوتاه')),
                ('price', models.PositiveBigIntegerField(blank=True, help_text='خالی بگذارید تا «استعلام قیمت» نمایش داده شود', null=True, verbose_name='قیمت (تومان)')),
                ('delivery_days', models.PositiveIntegerField(default=14, verbose_name='مدت تحویل (روز)')),
                ('revisions', models.PositiveIntegerField(default=2, verbose_name='تعداد بازنگری')),
                ('features', models.TextField(help_text='هر خط یک مورد', verbose_name='امکانات پکیج')),
                ('is_featured', models.BooleanField(default=False, verbose_name='پیشنهاد ویژه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'پکیج طراحی سایت',
                'verbose_name_plural': 'پکیج\u200cهای طراحی سایت',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=14, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('project_type', models.CharField(blank=True, max_length=150, verbose_name='نوع پروژه')),
                ('budget', models.CharField(blank=True, max_length=100, verbose_name='بودجه تقریبی')),
                ('message', models.TextField(verbose_name='توضیحات پروژه')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('contacted', 'تماس گرفته شد'), ('in_progress', 'در حال بررسی'), ('done', 'پایان یافته'), ('cancelled', 'لغو شده')], default='new', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicepackage', verbose_name='پکیج انتخابی')),
            ],
            options={
                'verbose_name': 'درخواست طراحی سایت',
                'verbose_name_plural': 'درخواست\u200cهای طراحی سایت',
                'ordering': ['-created_at'],
            },
        ),
    ]
