# Generated by Django 5.1.7 on 2025-06-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='full_address',
            field=models.TextField(max_length=300, verbose_name='آدرس کامل'),
        ),
    ]
