# Generated by Django 5.1.7 on 2025-06-30 00:34

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_address_full_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='پیام')),
                ('is_for_all_users', models.BooleanField(default=False, help_text='با فعال\u200cسازی، اعلان به همه کاربران ارسال می\u200cشود', verbose_name='برای همه کاربران')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('expiration_date', models.DateTimeField(blank=True, help_text='تاریخی که پس از آن اعلان به صورت خودکار حذف خواهد شد', null=True, verbose_name='تاریخ انقضا')),
                ('users', models.ManyToManyField(blank=True, help_text='لیست کاربرانی که این اعلان را دریافت می\u200cکنند', related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربران هدف')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200c ها',
                'ordering': ['-created_at'],
            },
        ),
    ]
