# Generated by Django 5.1.7 on 2025-06-08 00:17

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='نامک')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='متن مقاله')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='تصویر مقاله')),
                ('status', models.CharField(choices=[('draft', 'پیش نویس'), ('published', 'منتشر شود')], max_length=10, verbose_name='وضعیت')),
                ('views', models.IntegerField(default=0, editable=False, verbose_name='بازدید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده مقاله')),
                ('category', models.ManyToManyField(related_name='articles', to='blog.category', verbose_name='دسته بندی مربوطه')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
