# Generated by Django 5.1.7 on 2026-10-05 11:29

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0008_coupon_maximum_discount_coupon_minimum_order_amount_and_more'),
        ('product', '0015_digitalasset_file_size_digitalasset_file_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=32, max_length=40, prefix='', unique=True, verbose_name='توکن دانلود')),
                ('max_downloads', models.PositiveIntegerField(default=5, verbose_name='حداکثر تعداد دانلود')),
                ('download_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='تعداد دانلود انجام شده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_tokens', to='cart.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_tokens', to='product.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_tokens', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'توکن دانلود',
                'verbose_name_plural': 'توکن\u200cهای دانلود',
                'ordering': ['-created_at'],
            },
        ),
    ]
