# Generated by Django 5.1.7 on 2025-06-17 03:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد تخفیف')),
                ('discount_type', models.CharField(choices=[('percentage', 'درصدی'), ('fixed', 'مبلغ ثابت')], max_length=10, verbose_name='نوع تخفیف')),
                ('discount_value', models.IntegerField(verbose_name='مقدار تخفیف')),
                ('max_usage', models.IntegerField(blank=True, null=True, verbose_name='حداکثر استفاده')),
                ('usage_count', models.IntegerField(default=0, verbose_name='تعداد استفاده شده')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='معتبر از')),
                ('valid_to', models.DateTimeField(verbose_name='معتبر تا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'کوپن تخفیف',
                'verbose_name_plural': 'کوپن\u200cهای تخفیف',
            },
        ),
    ]
