# Generated by Django 5.1.7 on 2025-06-27 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cart_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'سبد خرید', 'verbose_name_plural': 'سبد های خرید'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'آیتم سبد خرید', 'verbose_name_plural': 'آیتم\u200c های سبد خرید'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'کوپن تخفیف', 'verbose_name_plural': 'کوپن \u200cهای تخفیف'},
        ),
    ]
