# Generated by Django 5.1.7 on 2026-10-05 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_order_items_data_alter_order_cart'),
        ('product', '0015_digitalasset_file_size_digitalasset_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='maximum_discount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='سقف تخفیف'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='minimum_order_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='حداقل مبلغ سفارش'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='per_user_limit',
            field=models.PositiveIntegerField(default=0, verbose_name='محدودیت برای هر کاربر'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_snapshot', models.CharField(max_length=300, verbose_name='عنوان هنگام خرید')),
                ('unit_price', models.PositiveIntegerField(verbose_name='قیمت واحد')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.PositiveIntegerField(verbose_name='مجموع')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='cart.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
                'indexes': [models.Index(fields=['product'], name='cart_orderi_product_edba2f_idx'), models.Index(fields=['order'], name='cart_orderi_order_i_c38a6b_idx')],
            },
        ),
    ]
