# Generated by Django 5.1.7 on 2026-10-05 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_coupon_maximum_discount_coupon_minimum_order_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'آیتم سبد خرید', 'verbose_name_plural': 'آیتم\u200c های سبد خرید'},
        ),
    ]
