# Generated by Django 5.1.7 on 2026-10-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_cartitem_options'),
        ('product', '0016_alter_product_options_alter_productcategory_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='برای محصولات دانلودی عدد ۱ ثبت می\u200cشود', verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=models.IntegerField(default=0, verbose_name='هزینه ارسال (محصولات دیجیتال: صفر)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده - آماده دانلود'), ('processing', 'در حال پردازش'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت سفارش'),
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='color',
        ),
    ]
