# Generated by Django 5.1.7 on 2026-10-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_cartitem_unique_together_remove_order_address_and_more'),
        ('product', '0018_enforce_storefront_invariants'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 1)), name='cart_item_quantity_exactly_one'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('discount_value__gte', 0)), name='coupon_discount_value_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('usage_count__gte', 0)), name='coupon_usage_count_nonnegative'),
        ),
    ]
