# Generated by Django 5.1.7 on 2026-10-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_enforce_storefront_invariants'),
        ('product', '0018_enforce_storefront_invariants'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='order_item_unique_product_per_order'),
        ),
    ]
